/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { ServiceRegistration } from "./ServiceRegistration";
import { ServiceRegistrationCountArgs } from "./ServiceRegistrationCountArgs";
import { ServiceRegistrationFindManyArgs } from "./ServiceRegistrationFindManyArgs";
import { ServiceRegistrationFindUniqueArgs } from "./ServiceRegistrationFindUniqueArgs";
import { DeleteServiceRegistrationArgs } from "./DeleteServiceRegistrationArgs";
import { ServiceRegistrationService } from "../serviceRegistration.service";
@graphql.Resolver(() => ServiceRegistration)
export class ServiceRegistrationResolverBase {
  constructor(protected readonly service: ServiceRegistrationService) {}

  async _serviceRegistrationsMeta(
    @graphql.Args() args: ServiceRegistrationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [ServiceRegistration])
  async serviceRegistrations(
    @graphql.Args() args: ServiceRegistrationFindManyArgs
  ): Promise<ServiceRegistration[]> {
    return this.service.serviceRegistrations(args);
  }

  @graphql.Query(() => ServiceRegistration, { nullable: true })
  async serviceRegistration(
    @graphql.Args() args: ServiceRegistrationFindUniqueArgs
  ): Promise<ServiceRegistration | null> {
    const result = await this.service.serviceRegistration(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => ServiceRegistration)
  async deleteServiceRegistration(
    @graphql.Args() args: DeleteServiceRegistrationArgs
  ): Promise<ServiceRegistration | null> {
    try {
      return await this.service.deleteServiceRegistration(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
